# Generated by Django 4.2.7 on 2023-12-06 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0003_rename_data_restaurant_date"),
        ("burgers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="burger",
            name="restaurant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="burger",
                to="restaurant.restaurant",
            ),
        ),
    ]
