# Generated by Django 4.2.7 on 2023-12-02 06:49

from django.db import migrations, models
import helpers.media_upload


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restaurant_name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=helpers.media_upload.upload_restaurant_image,
                    ),
                ),
            ],
        ),
    ]
