# Generated by Django 4.2.7 on 2023-12-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="data",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
