# Generated by Django 4.2.5 on 2024-01-13 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0003_rename_data_restaurant_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurant",
            old_name="data",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="owner",
        ),
    ]
